# =============================================================================
# File: /opt/ansible-k3s-cluster/cluster-dmesg-report.yml
# =============================================================================
# Purpose:
#   Collect the last 200 lines of dmesg output from each cluster node. Useful
#   for diagnosing kernel issues, driver failures, or boot anomalies.
#
# Usage:
#   ansible-playbook \
#     -i /opt/ansible-k3s-cluster/inventory/hosts \
#     /opt/ansible-k3s-cluster/cluster-dmesg-report.yml
#
# Notes:
#   - Does not modify system state.
# =============================================================================

---
- hosts: k3s_cluster
  become: yes

  tasks:
    - name: Collect dmesg output
      shell: dmesg | tail -n 200
      register: dmesg_out

    - name: Display dmesg summary
      debug:
        msg: "{{ dmesg_out.stdout }}"
