# =============================================================================
# File: /opt/ansible-k3s-cluster/cluster-swap-report.yml
# =============================================================================
# Purpose:
#   Generate a cluster-wide swap usage report including:
#     - Swap total
#     - Swap used
#     - Swap free
#     - Swap device presence
#
# Usage:
#   ansible-playbook \
#     -i /opt/ansible-k3s-cluster/inventory/hosts \
#     /opt/ansible-k3s-cluster/cluster-swap-report.yml
#
# Notes:
#   - Useful for diagnosing memory pressure and OOM conditions.
# =============================================================================

---
- hosts: k3s_cluster
  become: yes

  tasks:
    - name: Show swap summary
      shell: swapon --show || true
      register: swap

    - name: Show memory summary
      shell: free -h
      register: mem

    - name: Display swap report
      debug:
        msg:
          - "Swap: {{ swap.stdout }}"
          - "Memory: {{ mem.stdout }}"
