# =============================================================================
# File: /opt/ansible-k3s-cluster/cluster-network-firewall.yml
# =============================================================================
# Purpose:
#   Generate a cluster-wide firewall and ruleset report including:
#     - iptables rules
#     - nftables rules (if present)
#     - distccd port visibility
#     - k3s port visibility
#
# Usage:
#   ansible-playbook \
#     -i /opt/ansible-k3s-cluster/inventory/hosts \
#     /opt/ansible-k3s-cluster/cluster-network-firewall.yml
#
# Notes:
#   - Useful for diagnosing blocked distcc traffic or k3s networking failures.
# =============================================================================

---
- hosts: k3s_cluster
  become: yes

  tasks:
    - name: Show iptables rules
      shell: iptables -L -n -v 2>/dev/null
      register: ipt

    - name: Show nftables rules
      shell: nft list ruleset 2>/dev/null || true
      register: nft

    - name: Check distccd port
      shell: ss -tulnp | grep 3632 || true
      register: distcc

    - name: Display firewall report
      debug:
        msg:
          - "iptables: {{ ipt.stdout }}"
          - "nftables: {{ nft.stdout }}"
          - "distccd port: {{ distcc.stdout }}"
