# =============================================================================
# File: /opt/ansible-k3s-cluster/distcc-status.yml
# =============================================================================
# Purpose:
#   Display real-time distcc status across all cluster nodes. This includes:
#     - distccd service state
#     - active distccd processes
#     - listening ports
#
# Usage:
#   ansible-playbook \
#     -i /opt/ansible-k3s-cluster/inventory/hosts \
#     /opt/ansible-k3s-cluster/distcc-status.yml
#
# Notes:
#   - Useful during active distributed kernel builds.
# =============================================================================

---
- hosts: k3s_cluster
  become: yes

  tasks:
    - name: Check distccd service
      systemd:
        name: distccd
        state: started
      register: svc

    - name: Show distccd processes
      shell: ps aux | grep distccd | grep -v grep
      register: ps_out

    - name: Check port 3632
      shell: ss -tulpn | grep 3632 || true
      register: port_out

    - name: Display distcc status summary
      debug:
        msg:
          - "Service: {{ svc }}"
          - "Processes: {{ ps_out.stdout }}"
          - "Port 3632: {{ port_out.stdout }}"
